# Generated by Django 3.2.9 on 2021-11-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
    ]
